### ISSUE TITLE
폐쇄관련 ToDo

### ISSUE THREAD

**Issue by sh-nam** [predict-interactive/liverbridge-close#8]
@knh-8701 @predictXM 
- [x] 기간조정 선확인: 30일로 조정
- [x] 자동메일 제작 및 테스트발송
- [x] 자동메일 발송리스트 확보
- [x] 자동메일 발송예약
- [x]  중단 시 파킹 페이지 처리: 해당 사이트는 폐쇄되었습니다. 불편을 드려 죄송하며 추후 더 나은 컨텐츠로 찾아뵙겠습니다. 
감사합니다. 길리어드사이언스코리아 LIVER BRIDGE 드림
- [x] 파킹페이지 제작
- [x] 파킹페이지 컨펌
- [x] 파킹페이지 퍼블리싱
- [x] 배포: 30일 아침. 출근후
- [x] 관리자 닫을 건지 확인 -> 콘텐츠관리, 이부스접속통계를 제외한 나머지 메뉴 삭제 
- [x] 채널 폐쇄, 채널친구 실명 -> 삭제, 카카오 계정 탈퇴 (30일 오전)
리버브리지 카카오채널 마스터 계정
ID : seorin.jeong@gilead.com
PW : gilead!!11!
- [x] DB는 콘텐츠 제외한 나머지 삭제
- [x] 사이트 서버에서 파킹페이지 제외한 나머지 삭제처리 
- [x] 검색노출 확인
- [x] 기타 원본 소스(front,admin,was) 백업, Github 저장 --> ZIP파일 전달
- 리버브릿지 DB: 이부스 때문에 유지
- 리버브릿지 서버: 이부스 때문에 유지
- [x] GA 폐쇄
- [x] Data Studio 폐쇄
- [ ] HCP 인증관련: 메일건, 메일 서버 폐쇄
- [x] 고객사 대상 폐쇄 공지

내부작업
- ~~[x] 콘텐츠 백업 <— 백업대상 콘텐츠 메뉴 --> 전달 (구글 클라이드 or Git 저장, 전달)~~
- ~~가입회원 DB 백업 및 기타 DB백업~~
- ~~도메인 폐쇄 여부~~
- ~~공지할 건지 (예. 한달 전 공지 폐쇄)0~~
- ~~리버브릿지 관리자, 이부스 (서브도메인)~~
- ~~이부스 EC2(서버) 확인 —> 만약 같이 있으면 같이 닫을지 결정~~
- ~~폐쇄 날짜, 시간~~

고객사 확인 필요한것  
- ~~폐쇄날짜, 시간~~
- ~~폐쇄 한달 전 공지내용 및 대상자 (가입자 중 메일 수신동의한 사람에게만 발송하는지 확인필요)~~
- ~~카카오채널 폐쇄여부 확인 필요: 폐쇄~~
- ~~리버브릿지의 2차 도메인으로 사용되고있는 e-booth들 폐쇄여부 (e-booth들 폐쇄 안할 시 리버브릿지 도메인은 유지되어야하며, 리버브릿지 사이트는 파킹페이지 등으로 처리 필요할 듯 합니다.)~~
- ~~컨텐츠 백업대상 확인 필요 (아래 컨텐츠들 외 노출기간 지난 컨텐츠들도 백업 필요한지 확인 필요)~~

연결사이트 참조
[https://harvoni2.liverbridge.co.kr](https://harvoni2.liverbridge.co.kr/)  
[https://vemlidy2.liverbridge.co.kr](https://vemlidy2.liverbridge.co.kr/)  
[http://hbv.liverbridge.co.kr](http://hbv.liverbridge.co.kr/)  
[http://hcv.liverbridge.co.kr](http://hcv.liverbridge.co.kr/) (편집됨)
